name: Build
on:
  push:
    tags:
      - '0.*.*'
    paths-ignore:
      - '.github/workflows/x-*.yml'
  workflow_dispatch: # manually-triggered runs

permissions:
  # allowed to create releases (ref. https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs)
  contents: write

concurrency:
  # cancel pending runs when a PR gets updated (ref. https://github.com/rust-lang/rust/blob/75fd074338801fba74a8cf7f8c48c5c5be362d08/.github/workflows/ci.yml#L35)
  group: ${{ github.head_ref || github.run_id }}-${{ github.actor }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build
    runs-on: macos-latest

    env: # use tag version, if available, falling back to 0.13.0 (stable)
      CBOR_VERSION: "${{ startsWith(github.ref, 'refs/tags/0.') && github.ref_name || '0.13.0' }}"
      PUBLISH_RELEASE: "${{ startsWith(github.ref, 'refs/tags/0.') && '1' || '0' }}"

    steps:
    - name: checkout
      uses: actions/checkout@v6

    - name: build
      run: scripts/build.sh

    - name: publish native libraries
      uses: actions/upload-artifact@v6
      with:
        name: "cbor-${{ env.CBOR_VERSION }}"
        retention-days: 5
        if-no-files-found: "error"
        path: |
          build/cbor-build-${{ env.CBOR_VERSION }}/iphoneos/**
          build/cbor-build-${{ env.CBOR_VERSION }}/iphonesimulator/**
          build/cbor-build-${{ env.CBOR_VERSION }}/macosx/**

    - name: publish xcframework
      uses: actions/upload-artifact@v6
      with:
        name: "cbor-${{ env.CBOR_VERSION }}.xcframework"
        retention-days: 5
        if-no-files-found: "error"
        path: |
          build/cbor-build-${{ env.CBOR_VERSION }}/CBOR.xcframework

    - name: pack release artifacts
      if: "success() && env.PUBLISH_RELEASE == '1'"
      run: scripts/release.sh

    - name: create release
      if: "success() && env.PUBLISH_RELEASE == '1'"
      uses: softprops/action-gh-release@v2
      with:
        name: "${{ env.CBOR_VERSION }}"
        draft: true
        prerelease: false
        generate_release_notes: false
        fail_on_unmatched_files: true
        files: |
          build/cbor-build-${{ env.CBOR_VERSION }}/cbor.tar.gz
          build/cbor-build-${{ env.CBOR_VERSION }}/CBOR.xcframework.tar.gz
